#a docker compose file starting a redis server and the container as defined in dockerfileFrontEndFlaskLocal
version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  web:
    image: vismop
    build:
      context: .
      dockerfile: dockerfileFrontEndFlaskLocal
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GUNICORN_PORT=${GUNICORN_PORT}
    ports:
      - "${GUNICORN_PORT}:5001"
    depends_on:
      - redis
